spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/sellercloud?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
